<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Jint" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <Using Include="Bunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../Shared/text-vectors.json" Link="Shared/text-vectors.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/Sipos.Resume.Theme.Operandor/wwwroot/js/*.js" LinkBase="Scripts" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Sipos.Resume.Theme.Operandor/Sipos.Resume.Theme.Operandor.csproj" />
  </ItemGroup>

</Project>
