<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Sipos.Resume.Generation/Sipos.Resume.Generation.csproj" />
  </ItemGroup>

</Project>
