<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../Shared/text-vectors.json" Link="Shared/text-vectors.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../Shared/jsonresume-schema.json" Link="Shared/jsonresume-schema.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../samples/plain-json-resume/content/resume.en.json" Link="Shared/plain-resume.en.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Sipos.Resume.Core/Sipos.Resume.Core.csproj" />
  </ItemGroup>

</Project>
